[package]
name = "ivf"
version = "0.1.0"
authors = ["gibix <gibix@riseup.net>"]

[dependencies]
nom = "5.0"
av-bitstream = "0.1"
av-format = "0.2"
av-data = "0.2"
log = "0.4"

[dev-dependencies]
tempfile = "3"
structopt = "0.3"
pretty_env_logger = "0.4"
